name: Spring Boot CI Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Unit Tests with CouchDB
    runs-on: ubuntu-latest

    services:
      couchdb:
        image: couchdb:3.3
        ports:
          - 5984:5984
        env:
          COUCHDB_USER: admin
          COUCHDB_PASSWORD: admin123
        options: >-
          --health-cmd="curl --fail http://localhost:5984/_up"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests with Maven
        env:
          COUCHDB_URL: http://admin:admin123@localhost:5984
        run: mvn clean test

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: test # Runs only if tests succeed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR with Maven
        run: mvn clean package

      - name: Show JAR file (demo)
        run: ls -l target/*.jar

      - name: Simulate Deployment
        run: echo "🚀 Simulated deployment of the built application."
